# İzmir için Kira Tahmin Uygulaması

In [148]:
import os
import numpy as np
import pandas as pd

In [150]:
def drop_columns(df,cols):
    for col in cols:
        try:
            df.drop([col],axis=1, inplace=True)
        except Exception as e:
            print(f"Bir hata oluştur{e}")

In [151]:
files = os.listdir("hepsiemlak")
df = pd.concat([pd.read_csv(f"hepsiemlak/{file}") for file in files], ignore_index=True)

In [153]:
cols = [ 'photo-count',  'list-view-date','left',  'list-view-header','list-view-location', 'img-wrp href', 'he-lazy-image src','listing-card--owner-info__firm-name', 'he-lazy-image src 2', 'wp-btn']
drop_columns(df, cols)

In [154]:
df["location"] = df["img-link href"].apply(lambda x:x.split("/")[3])
df["city"] = df["location"].str.split("-").str[0]
df["district"] = df["location"].str.split("-").str[1]
df["neighborhood"] = df["location"].str.split("-").str[2:-1]
df["neighborhood"] = df["neighborhood"].apply(lambda x: "_".join(x))
print(df["neighborhood"].unique())

['torbali' 'alsancak' 'murat_reis' 'sogukkuyu' 'r_sevket_ince' 'gulyaka'
 'adatepe' 'yali' 'ahmet_taner_kislali' 'erzene' 'muammer_akar'
 'mavisehir' 'manavkuyu' 'colak_ibrahim_bey' 'inonu' 'kazimdirik'
 'ayrancilar' 'ornekkoy' 'esenlik' 'alacati' 'vatan' 'altinyunus' 'cagdas'
 'mithatpasa' 'zafertepe' '9_eylul' 'atakent' 'ugur_mumcu' 'atifbey'
 'tekeli_ataturk' 'yenigun' 'ozbek' 'gazipasa' 'kultur' 'cay' 'yakakent'
 'reis' 'ahihidir' 'beyazevler' 'demirkopru' 'inkilap' 'maliyeciler'
 'golcukler' 'balatcik' 'egitim' 'cankaya' 'yamanlar' 'korfez' 'ataturk'
 'bostanli' 'dedebasi' 'cumhuriyet' 'muratbey' 'kurucesme' 'onur'
 'kasimpasa' 'mustafa_kemal_ataturk' 'akarca' 'egridere' 'kuscular'
 'mansuroglu' 'arap_hasan' 'mevlana' 'atasehir' 'semikler' 'ulus'
 'kazimpasa' 'donanmaci' 'gulbahce' 'doganay' 'fahrettin_altay'
 'fevzi_cakmak' 'bahcelievler' 'dumlupinar' 'tersane' 'kemal_reis'
 'postacilar' 'kozagac' 'yedi_eylul' 'guzelyali' 'zubeyde_hanim'
 'istiklal' 'gazi_mustafa_kemal' 'tepekule

In [155]:
drop_columns(df,["location","img-link href"])

In [156]:
print(df[["city","district","neighborhood"]].sample(50))

       city     district        neighborhood
3208  izmir      menemen          ugur_mumcu
3187  izmir        konak           yesiltepe
1892  izmir         foca         kazim_dirik
445   izmir   karabaglar        muammer_akar
383   izmir         tire                toki
365   izmir   karabaglar            gunaltay
2764  izmir      bornova             mevlana
1626  izmir    karsiyaka             alaybey
769   izmir        konak            alsancak
2848  izmir   karabaglar     kazim_karabekir
662   izmir   karabaglar             poligon
1522  izmir      torbali          ayrancilar
1628  izmir        cigli      sasalli_merkez
635   izmir     menderes            gazipasa
3201  izmir   karabaglar          arap_hasan
957   izmir      menemen   85_yil_cumhuriyet
1251  izmir      menemen          ugur_mumcu
2560  izmir      menemen             ataturk
2829  izmir      bornova             mevlana
2625  izmir     bayrakli           sogukkuyu
1116  izmir         buca             ataturk
484   izmi

In [158]:
print(df["celly"])

0       2 +\n                          1
1       3 +\n                          1
2       3 +\n                          1
3       3 +\n                          1
4       1 +\n                          1
                      ...               
3237    3 +\n                          1
3238    2 +\n                          1
3239    2 +\n                          1
3240    1 +\n                          1
3241    3 +\n                          1
Name: celly, Length: 3242, dtype: object


In [159]:
df["celly"] = df["celly"].apply(lambda x: x.replace("Stüdyo","1+1"))
df["celly"] = df["celly"].apply(lambda x: x.replace("\n",""))
df["room"] = df["celly"].apply(lambda x: x.split("+")[0]).astype(int)
df["living_room"] = df["celly"].apply(lambda x: x.split("+")[1]).astype(int)

In [160]:
print(df["room"].unique())
print(df["living_room"].unique())

[2 3 1 5 4 6 7]
[ 1  2 10  0 11  3  5]


In [161]:
drop_columns(df,["celly"])
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3242 entries, 0 to 3241
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  3242 non-null   object
 1   celly 2          3242 non-null   object
 2   celly 3          3242 non-null   object
 3   celly 4          3076 non-null   object
 4   city             3242 non-null   object
 5   district         3242 non-null   object
 6   neighborhood     3242 non-null   object
 7   room             3242 non-null   int64 
 8   living_room      3242 non-null   int64 
dtypes: int64(2), object(7)
memory usage: 228.1+ KB
None


In [162]:
print(df["celly 2"])

0       125 m²
1       145 m²
2       110 m²
3       125 m²
4        70 m²
         ...  
3237    130 m²
3238     78 m²
3239     75 m²
3240     50 m²
3241    130 m²
Name: celly 2, Length: 3242, dtype: object


In [163]:
df["celly 2"] = df["celly 2"].apply(lambda x: x.replace(".", ""))
df["area"] = df["celly 2"].apply(lambda x: x.split(" ")[0]).astype(int)

In [164]:
print(df["area"])

0       125
1       145
2       110
3       125
4        70
       ... 
3237    130
3238     78
3239     75
3240     50
3241    130
Name: area, Length: 3242, dtype: int64


In [165]:
drop_columns(df, ["celly 2"])

In [166]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3242 entries, 0 to 3241
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  3242 non-null   object
 1   celly 3          3242 non-null   object
 2   celly 4          3076 non-null   object
 3   city             3242 non-null   object
 4   district         3242 non-null   object
 5   neighborhood     3242 non-null   object
 6   room             3242 non-null   int64 
 7   living_room      3242 non-null   int64 
 8   area             3242 non-null   int64 
dtypes: int64(3), object(6)
memory usage: 228.1+ KB
None


In [167]:
print(df["celly 3"].unique())

['10\n                        Yaşında'
 '35\n                        Yaşında'
 '31\n                        Yaşında'
 '16\n                        Yaşında'
 '29\n                        Yaşında'
 '7\n                        Yaşında'
 '25\n                        Yaşında'
 '33\n                        Yaşında'
 '30\n                        Yaşında'
 '5\n                        Yaşında'
 '26\n                        Yaşında' 'Sıfır Bina'
 '4\n                        Yaşında'
 '36\n                        Yaşında'
 '42\n                        Yaşında'
 '1\n                        Yaşında' '3\n                        Yaşında'
 '15\n                        Yaşında'
 '12\n                        Yaşında'
 '6\n                        Yaşında'
 '19\n                        Yaşında'
 '21\n                        Yaşında'
 '22\n                        Yaşında'
 '11\n                        Yaşında'
 '32\n                        Yaşında'
 '8\n                        Yaşında'
 '20\n              

In [168]:
df["celly 3"] =  df["celly 3"].apply(lambda x: x.replace("Sıfır Bina", "0 Yaşında"))
df["celly 3"] = df["celly 3"].apply(lambda x: x.replace("\n"," "))
df["age"] = df["celly 3"].apply(lambda x : x.split(" ")[0]).astype(int)

In [169]:
print(df["age"].unique())

[ 10  35  31  16  29   7  25  33  30   5  26   0   4  36  42   1   3  15
  12   6  19  21  22  11  32   8  20   2  18  17  40  45  28  14   9  38
  13  50  24  27  39  23  44  60  47  37 100  34  55  43]


In [170]:
drop_columns(df,["celly 3"])

In [174]:
print(df["celly 4"].unique())

['2. Kat' '4. Kat' '5. Kat' '1. Kat' '0. Kat' '3. Kat' 'nan' '6. Kat'
 '8. Kat' '7. Kat' '10. Kat' '-1. Kat' '9. Kat' '12. Kat' '13. Kat'
 '-2. Kat' '17. Kat' '11. Kat' '21. Kat' '14. Kat' '15. Kat' '-3. Kat'
 '19. Kat' '18. Kat' '16. Kat']


In [175]:
replace_dict = {
    'Kot 1': '-1. Kat',
    'Kot 2': '-2. Kat',
    'Kot 3': '-3. Kat',
    'Bahçe Katı' : '0. Kat',
    'Ara Kat' : '3. Kat',
    'Zemin' : '0. Kat',
    'Yüksek Giriş' : '1. Kat',
    'Villa Katı' : '0. Kat',
    'Giriş Katı' : '0. Kat',
    'En Üst Kat' : '5. Kat',
    'Çatı Katı' : '5. Kat',
    'Bodrum ve Zemin' : '0. Kat',
    'Yarı Bodrum' : '0. Kat',
    'Teras Katı' : '5. Kat',
    '21 ve üzeri' : '21. Kat',
    'Bodrum' : '0. Kat',
    'Tripleks' : '0. Kat', 
    'nan' : '2. Kat'
}
df["celly 4"] = df["celly 4"].replace(replace_dict.keys(), replace_dict.values()).astype(str)
df["celly 4"].dropna(inplace=True)
df["floor"] = df["celly 4"].apply(lambda x: x.split(".")[0]).astype(int)


In [176]:
print(df["floor"].unique())

[ 2  4  5  1  0  3  6  8  7 10 -1  9 12 13 -2 17 11 21 14 15 -3 19 18 16]


In [178]:
drop_columns(df, ["celly 4"])

In [180]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3242 entries, 0 to 3241
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  3242 non-null   object
 1   city             3242 non-null   object
 2   district         3242 non-null   object
 3   neighborhood     3242 non-null   object
 4   room             3242 non-null   int64 
 5   living_room      3242 non-null   int64 
 6   area             3242 non-null   int64 
 7   age              3242 non-null   int64 
 8   floor            3242 non-null   int64 
dtypes: int64(5), object(4)
memory usage: 228.1+ KB
None
